version: '3.8'

services:
  # frontend:
  #   image: frontend_image
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend

  # backend:
  #   image: backend_image
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - database

  database:
    image: mongo:latest
    container_name: mongomg
    env_file:
      - backend/.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: ["--auth"]

volumes:
  mongo-data:
