version: '3.8'

services:
  # frontend:
  #   image: frontend_image
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend

  # backend:
  #   image: backend_image
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - database

  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    command: --auth

volumes:
  mongo_data:
