version: '3.8'

services:
  frontend:
    image: frontend_image
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - database

  backend:
    image: backend_image
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - backend/.env
    environment:
      - MONGO_HOST=database
    ports:
      - "8080:8080"
    networks:
      - database-network
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: mongomg
    restart: unless-stopped
    env_file:
      - backend/.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: ["--auth"]
    networks:
      - database-network


networks:
  database-network:
    driver: bridge
  
volumes:
  mongo-data:
