export const TAGS = [
    "Art",
    "Music",
    "Gaming",
    "Technology",
    "Science",
    "Health",
    "Education",
    "Business",
    "Food",
    "Travel",
    "Fashion",
    "Sports",
    "Environment",
    "Politics",
    "Other",
];

export const ALLOWED_EXTENSIONS = [
    "image/jpeg",
    "image/png",
    "image/gif",
    "image/bmp",
    "image/webp",
    "video/mp4",
    "video/mpeg",
    "video/quicktime",
    "video/x-msvideo",
    "video/x-ms-wmv",
];
