export const TAGS = [
    "Art",
    "Music",
    "Gaming",
    "Technology",
    "Science",
    "Health",
    "Education",
    "Business",
    "Food",
    "Travel",
    "Fashion",
    "Sports",
    "Environment",
    "Politics",
    "Other",
]